# Generated by Django 2.0.5 on 2018-05-05 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 5, 22, 24, 2, 63220), verbose_name='Опубликована'),
        ),
    ]
