# Generated by Django 2.0.5 on 2018-05-07 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180505_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='new_image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 7, 10, 55, 48, 180135), verbose_name='Опубликована'),
        ),
    ]
