# Generated by Django 2.0.5 on 2018-05-07 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180507_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_image',
            field=models.ImageField(upload_to='imagepool/%Y/%m', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 7, 11, 2, 4, 286027), verbose_name='Опубликована'),
        ),
    ]
