# Generated by Django 2.0.5 on 2018-05-07 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180507_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='new_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 7, 11, 2, 38, 539323), verbose_name='Опубликована'),
        ),
    ]
