# Generated by Django 2.0.5 on 2018-05-07 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180507_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='image',
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 7, 11, 7, 5, 396582), verbose_name='Опубликована'),
        ),
    ]
