# Generated by Django 2.0.5 on 2018-05-07 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20180507_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default=' ', upload_to='imagepool/%Y/%m', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 7, 11, 30, 29, 679949), verbose_name='Опубликована'),
        ),
    ]
