# Generated by Django 2.0.5 on 2018-05-07 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20180507_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='image',
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 7, 12, 18, 25, 449137), verbose_name='Опубликована'),
        ),
    ]
