# Generated by Django 2.0.5 on 2018-05-07 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20180507_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 7, 12, 30, 58, 41024), verbose_name='Опубликована'),
        ),
    ]
