# Generated by Django 2.0.5 on 2018-05-08 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20180507_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 8, 20, 4, 51, 215158), verbose_name='Опубликована'),
        ),
    ]
