# Generated by Django 2.0.5 on 2018-05-10 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20180508_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 10, 15, 26, 44, 670638), verbose_name='Опубликована'),
        ),
    ]
