# Generated by Django 2.0.5 on 2018-05-10 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20180510_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 10, 15, 36, 48, 944013), verbose_name='Опубликована'),
        ),
    ]
