# Generated by Django 2.0.5 on 2018-05-10 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20180510_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 10, 18, 40, 50, 478033), verbose_name='Опубликована'),
        ),
    ]
