# Generated by Django 2.0.5 on 2018-05-15 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20180510_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 15, 20, 14, 18, 858593), verbose_name='Опубликована'),
        ),
    ]
