# coding=utf-8
"""
Django settings for this website project.

Generated by wooyek/cookiecutter-django-website

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/

# Before go-live check if your settings are suitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/
"""

from __future__ import absolute_import, unicode_literals
import os
import logging
from pathlib import Path

logging.basicConfig(format='%(asctime)s %(levelname)-7s %(thread)-5d %(filename)s:%(lineno)s | %(funcName)s | %(message)s', datefmt='%H:%M:%S')
logging.getLogger().setLevel(logging.DEBUG)
logging.disable(logging.NOTSET)

logging.debug("Settings loading: %s" % __file__)

# ╭────────────────────────────────────────────────────────────────────────────
# │ This is a composite strategy for setting up django website instance.
# │ We import default component settings and customise them below in this file
# │ To disable or enable particular component just comment or uncomment a component import

# noinspection PyUnresolvedReferences
from .components.debug_toolbar import *
from .components.telegram import *
#from .components.django_assets import *
# from .components.celery import *
from .components.import_export import *
#from .components.pycountry import *
from .components.sentry import *
# from .components.newrelic import *
# from .components.django_opt_out import *
# from .components.django_email_queue import *
# from .components.django_filer import *
# from .components.oauth_toolkit import *
# from .components.rest_framework import *
# from .components.gis import *
# from .components.intercom import *
# from .components.pure_pagination import *

if 'GOOGLE_STORAGE_ID' in os.environ:
    from .components.google_cloud_storage import *

# Other imports can cause change in core settings
# we should import core last
from .components.core import env, BASE_DIR
from .components.core import *

# │ Customizations made for this project only should go bellow
# ╰────────────────────────────────────────────────────────────────────────────


INSTALLED_APPS += (
    #'bootstrapform',
    # 'django_babel',
    # 'guardian',
    #'reversion',
    # 'django_filters',
    'django_powerbank',
    'django_error_views.apps.DjangoErrorViewsConfig',
    # 'localflavor',
    # 'django_gravatar',
    # 'misc.choose_language',
    #'picropper.apps.PicropperConfig',
)

# AUTH_USER_MODEL = 'picropper.CustomUser'

LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow'

# https://docs.djangoproject.com/en/1.9/topics/i18n/translation/#how-django-discovers-language-preference
import django_error_views

LOCALE_PATHS = [
    str(Path(django_error_views.__file__).parent / 'locales'),
    str(BASE_DIR / 'locales'),
]


